export const STRINGS = {
  app: {
    name: 'KURA Clínica',
  },
  auth: {
    login: 'Entrar',
    email: 'E-mail',
    senha: 'Senha',
    esqueciSenha: 'Esqueci minha senha',
    emailPlaceholder: 'seu@email.com',
    senhaPlaceholder: 'Mínimo 6 caracteres',
    erroCredenciais: 'E-mail ou senha incorretos',
    erroRede: 'Sem conexão. Verifique sua internet.',
  },
  dashboard: {
    titulo: 'Dashboard',
    consultasHoje: 'Consultas hoje',
    pacientesAtendidos: 'Pacientes atendidos',
    alertasAtivos: 'Alertas ativos',
    teleorientacoes: 'Teleorientações',
    proximosAtendimentos: 'Próximos atendimentos',
    alertas: 'Alertas',
    semAlertas: 'Nenhum alerta ativo',
    semAtendimentos: 'Nenhum atendimento programado',
  },
  pacientes: {
    titulo: 'Pacientes',
    buscar: 'Buscar por nome ou tutor...',
    novo: '+ Novo',
    semResultados: 'Nenhum paciente encontrado',
    timeline: 'Histórico',
    vacinas: 'Vacinas',
    documentos: 'Documentos',
  },
  PACIENTES: {
    TITLE: 'Pacientes',
    SEARCH_PLACEHOLDER: 'Buscar pet ou tutor...',
    EMPTY_SEARCH: 'Nenhum paciente encontrado',
    EMPTY_LIST: 'Nenhum paciente cadastrado',
    COUNT_SINGULAR: '1 paciente',
    COUNT_PLURAL: (n: number) => `${n} pacientes`,
    NO_TUTOR: 'Sem tutor',
  },
  acoes: {
    novaConsulta: 'Nova consulta',
    teleorientacao: 'Teleorientação',
    receituario: 'Receituário',
    salvar: 'Salvar',
    cancelar: 'Cancelar',
    voltar: 'Voltar',
    enviar: 'Enviar',
    confirmar: 'Confirmar',
  },
  luna: {
    titulo: 'Luna AI',
    online: 'Luna online',
    offline: 'Luna offline',
  },
  configuracoes: {
    titulo: 'Configurações',
    perfil: 'Perfil',
    preferencias: 'Preferências',
    time: 'Time',
    temaEscuro: 'Tema escuro',
    sair: 'Sair',
  },
  agenda: {
    titulo: 'Agenda',
    semanaAnterior: 'Semana anterior',
    proximaSemana: 'Próxima semana',
    semConsultas: 'Nenhuma consulta neste dia',
  },
  erros: {
    generico: 'Algo deu errado. Tente novamente.',
    semConexao: 'Sem conexão com a internet.',
    naoEncontrado: 'Registro não encontrado.',
  },
  AUTH: {
    INVALID_CREDENTIALS: 'E-mail ou senha incorretos',
    NETWORK_ERROR: 'Sem conexão. Verifique sua internet.',
  },
  VALIDATION: {
    EMAIL_INVALID: 'E-mail inválido',
    PASSWORD_MIN: 'A senha deve ter no mínimo 6 caracteres',
  },
  LUNA: {
    TITLE: 'Luna IA',
    STATUS_ONLINE: 'Online',
    STATUS_DEGRADADO: 'Degradado',
    STATUS_OFFLINE: 'Offline',
    RELATORIO_TITLE: 'Relatório de Triagens',
    PERIODO_7: '7 dias',
    PERIODO_30: '30 dias',
    PERIODO_90: '90 dias',
    TOTAL_TRIAGENS: (n: number) => `Total de triagens: ${n}`,
    ENCAMINHADAS: (n: number) => `Encaminhadas para vet: ${n}`,
    ALERTAS_TITLE: 'Alertas gerados pela Luna',
    EMPTY_ALERTAS: 'Nenhum alerta ativo',
  },
} as const;
